### ISSUE TITLE
CVE: Unlock dependency to xmldom

### ISSUE THREAD

**Issue by joaomoreno** [TooTallNate/plist.js#105]
`xmldom<0.5.0` has a current CVE security alert: https://github.com/advisories/GHSA-h6q6-9hqw-rwfv

plist.js has a pretty hard lock against a very old version of `xmldom` which prevents adopting the fix: https://github.com/TooTallNate/plist.js/blob/master/package.json#L30

I was about to submit a PR, but I saw the current PR backlog and got discouraged. Is this project abandoned?

**Comment by joaomoreno** [comment]
Ended up submitting the PR: https://github.com/TooTallNate/plist.js/issues/105

**Comment by mreinstein** [comment]
>  I saw the current PR backlog and got discouraged. Is this project abandoned?

It's not abandoned per se, but it is really lacking any attention. Part of the problem is the tests have been failing for quite a while. Probably something having to do with sauce labs and/or zuul.

**Comment by mreinstein** [comment]
@TooTallNate are you around to help with this? I think it's probably just a matter of updating some credentials and embedding new keys for sauce labs in this repo.

**Comment by mreinstein** [comment]
![Uploading Screen Shot 2021-03-15 at 6.00.29 PM.png…]()

**Comment by joaomoreno** [comment]
> > I saw the current PR backlog and got discouraged. Is this project abandoned?
> 
> It's not abandoned per se, but it is really lacking any attention. Part of the problem is the tests have been failing for quite a while. Probably something having to do with sauce labs and/or zuul.

Sooooo.... would you be interested in getting GH Actions instead?

**Comment by mreinstein** [comment]
> would you be interested in getting GH Actions instead?

Does github actions include free cross browser testing? Because that's the main issue on why the tests are failing. 

I'm not opposed to switching to something better, but travis is not currently broken, and just switching to github actions without gaining cross browser testing capabilities doesn't solve the problem.

**Comment by joaomoreno** [comment]
> Does github actions include free cross browser testing? Because that's the main issue on why the tests are failing.

Yeah we use it in VS Code.

Anyway, I'm about to give up here, since we're not willing to wait. We will just stop using plist.js, simply because we can't afford to ship dependencies with security vulnerabilities.

**Comment by mreinstein** [comment]
> Yeah we use it in VS Code.

Well if you have more information you can point me at about how one might use this, I'm happy to take a look.


> we can't afford to ship dependencies with security vulnerabilities.

I've got some bad news for you; all software is shipping with security vulnerabilities whether they are listed in a database or not.

**Comment by joaomoreno** [comment]
> Well if you have more information you can point me at about how one might use this, I'm happy to take a look.

What do you mean?

**Comment by mreinstein** [comment]
> What do you mean?

I mean, if you have information on where I can go to figure out how to setup github actions with cross browser testing capabilities, I am happy to read through some guide and try to get that setup. I don't have any experience with github actions yet. If you know how to set this up, help would be appreciated.


> If we can't get this PR merged, we'll just fork plist.js or stop using it.

Again, I can't just merge PRs and do releases while tests are failing. No one is suggesting this can't be fixed, I'm just telling you what the current blocker is to actually solving this; getting the tests to pass.

**Comment by joaomoreno** [comment]
> I mean, if you have information on where I can go to figure out how to setup github actions with cross browser testing capabilities, I am happy to read through some guide and try to get that setup. I don't have any experience with github actions yet. If you know how to set this up, help would be appreciated.

Oh I see, got it. Unfortunately I don't have much time to guide you here. A quick google search got me:

- https://docs.github.com/en/actions/learn-github-actions
- https://github.com/microsoft/playwright-github-action

Thanks for the update.

**Comment by mreinstein** [comment]
Saucelabs finally got back to me, and they've granted my account access to testing resources!

Unfortunately, simply plugging in my credentials doesn't seem to solve the problem. I'm still seeing errors when the tests attempt to run via sauce.

I'm not really sure how to fix this. The problem is there are a lot of moving pieces; travis ci, sauce labs, zuul, mocha, a super outdated makefile, etc.

for now it seems, I'm stuck.

**Comment by Siedlerchr** [comment]
Maybe this helps https://blog.maximeheckel.com/posts/running-cross-browser-cypress-github-ci 
https://github.com/cypress-io/github-action

**Comment by mreinstein** [comment]
well, it's not ideal, I had to remove some tests, but I did manage to get the browser based tests somewhat working. This should be resolved in 3.0.2 via https://github.com/TooTallNate/plist.js/commit/e828f846ded15f3a074c76a39dc39c62cc598e39

**Comment by joaomoreno** [comment]
@mreinstein This is fantastic, thanks for all the hard work, it's really appreciated!
