### ISSUE TITLE
Plist write

### ISSUE THREAD

**Issue by wamatt** [TooTallNate/plist.js#12]
Anyone know if this module or any other fork supports writing to a Plist? Binary plist in particular. I wan't to update some properties in a `~/Library/Preferences` plist file.

**Comment by swapnarachapalli** [comment]
Hi,

Are these methods like  insert() , delete() or update() already available ? If so can i get some example to use it ?

It will be great help for me.  Also i saw in this thread that the plist can be read as json and then do the modification to this json, can u share this example ? i am newbee to scripting .

Regards,
Swapna
