### ISSUE TITLE
> I had added scripts generated by `volta completions powershell` to `Microsoft.PowerShell_profile.ps1` but that not working.

### ISSUE THREAD

**Issue by NIVEA77** [TooTallNate/plist.js#130]
> I had added scripts generated by `volta completions powershell` to `Microsoft.PowerShell_profile.ps1` but that not working.
> 
> 
> 
> **Platform information:**
> 
> - Windows 11: 22H2(22621.457)
> 
> - Powershell: 7.2.6
> 
> - Volta: 1.0.8

__Originally posted by @NIVEA77 in https://github.com/volta-cli/volta/issues/1312#issuecomment-1264482926__

**Comment by mreinstein** [comment]
I don't think you're posting this to the right repo; I have no clue what is being asked here, or what this has to do with plist.js
