### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'nodeName')

### ISSUE THREAD

**Issue by xiatian12345** [TooTallNate/plist.js#140]
my code:

var fs = require('fs');
var plist = require('plist');
var needParse = fs.readFileSync('com.qiuyuzhou.ShadowsocksX-NG.plist', 'utf8');
console.log(needParse);
var obj = plist.parse(needParse);
console.log(JSON.stringify(obj));

and then the error occurred

`
TypeError: Cannot read properties of null (reading 'nodeName')
    at Object.parse (/Users/xiatian/Desktop/temp/node_modules/plist/lib/parse.js:68:25)
`

**Comment by xiatian12345** [comment]
The plist file is here [https://github.com/xiatian12345/report/blob/main/com.qiuyuzhou.ShadowsocksX-NG.plist](url)

**Comment by oopses** [comment]
https://lvv.me/posts/2022/10/01_plutil_example/

plist 不都是xml格式的，目前plist.js只覆盖了xml部分的解析，其他的解析可以参考这个

**Comment by xiatian12345** [comment]
> https://lvv.me/posts/2022/10/01_plutil_example/
> 
> plist 不都是xml格式的，目前plist.js只覆盖了xml部分的解析，其他的解析可以参考这个

好的，多谢
