### ISSUE TITLE
Pass options to the xmlbuilder module

### ISSUE THREAD

**Issue by kannus** [TooTallNate/plist.js#72]
Error: Invalid character (�) in string: 💤 at index 0

While using the plist builder, if the XML string contains some sort of emoji UTF-8 character, the builder failed.  The xmlbuilder does support such characters but it requires an option (allowSurrogateChars) to be set to true.  It would be great if plist can allow this option to be passed through to the xmlbuilder.

**Comment by mreinstein** [comment]
@kannus I'd definitely accept a PR for this. If you do, please be sure to include tests, and update the documentation on relevant parameters that can be passed.

**Comment by kannus** [comment]
A zip file attached (the index.js needs plist, uuid and readlines from npm).  If I modify the build.js in plist to pass the opts to xmlbuilder.create(), then the plist can be successfully created.

[issue.zip](https://github.com/TooTallNate/plist.js/files/213892/issue.zip)

**Comment by mreinstein** [comment]
@kannus don't pass around file archives or other binary blobs. Please send a proper pull request.
