### ISSUE TITLE
Cannot use in webpack

### ISSUE THREAD

**Issue by armorik83** [TooTallNate/plist.js#77]
`plist@1.2.0`, `webpack@1.13.1`

```
ERROR in ./~/plist/lib/node.js
Module not found: Error: Cannot resolve module 'fs' in /node_modules/plist/lib
 @ ./~/plist/lib/node.js 5:9-22
```

`webpack` cannot be interpreted `require('fs')`. I think it should be running with webpack if you say clearly 'Mac OS X Plist parser/builder for Node.js and browsers'.
Could you support with webpack? thanks.

**Comment by armorik83** [comment]
https://github.com/TooTallNate/plist.js/blob/master/lib/plist.js#L18-L23

I thought that should be release the next major version removing this description. 😃

**Comment by mreinstein** [comment]
@armorik83 I haven't used webpack, is it possible to shim fs requires in webpack? If so, it should be possible to use plist.js. Perhaps there is some kind of loader/transform for it?

**Comment by TooTallNate** [comment]
Can you give v2.0.0 a try?

**Comment by mreinstein** [comment]
@TooTallNate if we're going to cut a major release it would  be nice to also get a solution to this in there too: https://github.com/TooTallNate/plist.js/issues/75

**Comment by armorik83** [comment]
Very cool. Thank you👏
