### ISSUE TITLE
Add changelog or details to "Releases"

### ISSUE THREAD

**Issue by mitchhentges** [TooTallNate/plist.js#78]
As a consumer of `plist.js`, it would be more convenient to handle the `v1.0.1`->`v2.0.1` upgrade if there changelog notes. I can look through the commit list, but it has information about project continuous integration, etc, and is therefore more work to filter.

However, this project is pretty awesome, so thanks for continuing to work on it, you champ :+1:

**Comment by TooTallNate** [comment]
Did you check out the [`History.md` file](https://github.com/TooTallNate/plist.js/blob/master/History.md)?

**Comment by mitchhentges** [comment]
Apparently not, glossed over the file tree really quickly. Thanks, sorry about that!
