### ISSUE TITLE
Parsing a null-string and re-building that file results in incorrect structure

### ISSUE THREAD

**Issue by taknuti** [TooTallNate/plist.js#79]
When parsing a file containing an empty string and re-building that JSON to a plist, the empty string will not be added, resulting in a key without a value (see example below). The fix might be simple on the 'parse' side, as there is an explicit null-check on parse.js@131: `if(isEmptyNode(node)) return null;`. This can be changed to `if(isEmptyNode(node)) return '';` as empty strings behave correctly.
However, this probably means null-values in JSON generated from other sources are affected as well, so perhaps this needs a fix on the build-side as well. 

Example code:

```
var plist = require('plist');
var xml = 
  '<?xml version="1.0" encoding="UTF-8"?>' +
  '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' +
  '<plist version="1.0">' +
    '<key>metadata</key>' +
    '<dict>' +
      '<key>ExampleKey</key>' +
      '<string></string>' +
      '<key>AnotherKey</key>' +
      '<string>Avalue</string>' +
    '</dict>' +
  '</plist>';

console.log(plist.build(plist.parse(xml)));
```

Output:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <array>
    <string>metadata</string>
    <dict>
      <key>ExampleKey</key>
      <key>AnotherKey</key>
      <string>Avalue</string>
    </dict>
  </array>
</plist>
```

**Comment by rnarian** [comment]
👍 

Just ran into the same problem:

```
<key>First Key</key>
</string>
<key>Second Key</key>
<string>Value</string>
```

... results in:

```
<key>First Key</key>
<key>Second Key</key>
<string>Value</string>
```

**Comment by kim3er** [comment]
@akofman's changes sort the problem for me.

**Comment by otmezger** [comment]
Can confirm, @akofman's fix worked for me on OS Sierra with Xcode 8.0

**Comment by njleonzhang** [comment]
Issue is still there in my environment:
```
    <key>NSMainNibFile</key>
    <string/>
    <key>NSMainNibFile~ipad</key>
    <string/>
```

to 

```
    <key>NSMainNibFile</key>
    <key>NSMainNibFile~ipad</key>
```

xcode 8.1
plist 2.0.1

**Comment by cmaart** [comment]
Still a problem

**Comment by mreinstein** [comment]
Hey sorry for the super long reply delay.   Can we get a PR for this? I'm happy to review/merge. Would be nice to get this in for the upcoming v4 release.

**Comment by taknuti** [comment]
> Hey sorry for the super long reply delay. Can we get a PR for this? I'm happy to review/merge. Would be nice to get this in for the upcoming v4 release.

It has indeed been a while ;) I just reread the comments and unless I'm mistaken this was fixed in https://github.com/TooTallNate/plist.js/pull/84. We are not using this package anymore and I'm not able to verify just now, but I think this issue van be closed.
