### ISSUE TITLE
[Feature request] Indent format and trailing line break option for build()

### ISSUE THREAD

**Issue by kamataryo** [TooTallNate/plist.js#92]
xcode seems to build plist with tab indent, but plist.js rebuild it with  2 white spaces.
This causes unnecessary diff under version control.

How about to add options for `build()` like below?
```
{
    indentStyle: 'tab' | 'space',
    indentSize: number,
    insertFinalNewLine: boolean,
}
```

**Comment by Nemo108** [comment]
@kamataryo build method actually receives options object as second argument. You can change **indention**, **newline** character, and add extra **offset** to every line (don't really know how it can be helpful).
```js
plist.build(json, {
	indent: '	', // Tab character
	offset: 2,
	newline: '\n'
});
```

**Comment by kamataryo** [comment]
@Nemo108 `plist.build()` results with below configuration looks to match better for that of xcode (Version 9.4.1).
```
plist.build(json, {
	indent: '	', // Tab character
	offset: -1,
	newline: '\n'
});
```

However, diff below still appears after `plist.build()`.
```
-       <string></string>
+       <string/>
```

xcode expands '<string/>' and `plist.build()` doesn't expands `<string/>`. On the other hand, `<true/>`  is not expanded by xcode. I have no idea with consistency of xcode's building of XML.

It might be difficult to keep following xcode's behavior. However the 2nd argument options saves lots of `git diff`, Anyway. Thanks a lot!
